title: JAK VYZRÁT NA COSPLAY
baseURL: https://jak-vyzrat-na-cosplay2.netlify.com
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Hlavní stránka
      url: /
      googleAnalytics: "UA-139302584-1"
      weight: 10
    - name: Archív
      identifier: post
      url: /post/
      weight: 20

params:
  description: 
  authors: 
